# Generated by Django 3.2.7 on 2021-12-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='color',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='size',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
